// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockMarketApp.Data;

namespace StockMarketApp.Data
{
    [DbContext(typeof(StockMarketContext))]
    [Migration("20190528124431_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("StockMarketApp.Models.Broker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Brokers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("34430d35-a8b0-4bdf-90fd-ca5add46a10b"),
                            Name = "Broker1"
                        });
                });

            modelBuilder.Entity("StockMarketApp.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BrokerId");

                    b.Property<Guid?>("ClientId");

                    b.Property<double>("Commission");

                    b.Property<double>("Price");

                    b.Property<int>("Quantity");

                    b.Property<Guid>("StockId");

                    b.HasKey("Id");

                    b.HasIndex("BrokerId");

                    b.HasIndex("ClientId");

                    b.HasIndex("StockId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("StockMarketApp.Models.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BrokerId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("BrokerId");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = new Guid("868e4d70-2648-43db-a584-2ba90e8ee407"),
                            BrokerId = new Guid("34430d35-a8b0-4bdf-90fd-ca5add46a10b"),
                            Name = "Client1"
                        },
                        new
                        {
                            Id = new Guid("19b8ca93-e1fc-477a-bf7b-2e40a6bc7f80"),
                            BrokerId = new Guid("34430d35-a8b0-4bdf-90fd-ca5add46a10b"),
                            Name = "Client2"
                        });
                });

            modelBuilder.Entity("StockMarketApp.Models.Stock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("Price");

                    b.HasKey("Id");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6426c117-0583-476b-a327-3863ef223e3a"),
                            Name = "Vianet",
                            Price = 16
                        },
                        new
                        {
                            Id = new Guid("b297fc93-986e-41d5-bbd9-4f90b084e937"),
                            Name = "Agritek",
                            Price = 46
                        },
                        new
                        {
                            Id = new Guid("58d5e484-0710-4f60-bbbe-dbff4096a91a"),
                            Name = "Akamai",
                            Price = 89
                        },
                        new
                        {
                            Id = new Guid("c4e8a875-df78-41c7-a438-abedaa36466c"),
                            Name = "Baidu",
                            Price = 20
                        },
                        new
                        {
                            Id = new Guid("c6eea4d4-108a-4e69-a24c-e30f9a3db27f"),
                            Name = "Blinkx",
                            Price = 93
                        },
                        new
                        {
                            Id = new Guid("16dfa69d-fbb6-43ae-b4cc-9cbbbf5e010f"),
                            Name = "Blucora",
                            Price = 84
                        },
                        new
                        {
                            Id = new Guid("eaa52192-3594-44e4-90d3-92f2c2dc5fbe"),
                            Name = "Boingo",
                            Price = 31
                        },
                        new
                        {
                            Id = new Guid("451e67ca-f0d7-4d36-87e6-a14da5ae9ea9"),
                            Name = "Brainybrawn",
                            Price = 2
                        },
                        new
                        {
                            Id = new Guid("ee5c7a6a-47d5-4683-a41a-8aa2db0611fd"),
                            Name = "Carbonite",
                            Price = 47
                        },
                        new
                        {
                            Id = new Guid("687854d8-0669-4f67-82e9-d7d75e5249a6"),
                            Name = "China Finance",
                            Price = 44
                        },
                        new
                        {
                            Id = new Guid("130be51f-0157-47f4-b718-fdff1e9c0a2e"),
                            Name = "ChinaCache",
                            Price = 84
                        },
                        new
                        {
                            Id = new Guid("c02a4db7-4e35-4f78-b623-7940a4498caa"),
                            Name = "ADR",
                            Price = 64
                        },
                        new
                        {
                            Id = new Guid("91172153-8ae8-47d7-91a4-046e36222feb"),
                            Name = "ChitrChatr",
                            Price = 92
                        },
                        new
                        {
                            Id = new Guid("aabbf10f-2139-469c-8091-0cec1af969e2"),
                            Name = "Cnova",
                            Price = 2
                        },
                        new
                        {
                            Id = new Guid("c0b6379c-9031-446d-84cb-cc4a2b8f1d28"),
                            Name = "Cogent",
                            Price = 59
                        },
                        new
                        {
                            Id = new Guid("f9a6ce28-652d-4ba3-9ff8-c4a8c6c34941"),
                            Name = "Crexendo",
                            Price = 93
                        },
                        new
                        {
                            Id = new Guid("5ab899ec-18cb-494d-959c-6347efaa20cf"),
                            Name = "CrowdGather",
                            Price = 84
                        },
                        new
                        {
                            Id = new Guid("a3877689-e1a3-4329-bfb9-4e6e92030286"),
                            Name = "EarthLink",
                            Price = 31
                        },
                        new
                        {
                            Id = new Guid("04e15309-386c-4f90-948b-7db325607fb9"),
                            Name = "Eastern",
                            Price = 27
                        },
                        new
                        {
                            Id = new Guid("1b44c460-5bdc-4adc-8cf2-2bbe86848a49"),
                            Name = "ENDEXX",
                            Price = 28
                        },
                        new
                        {
                            Id = new Guid("6a35264f-cce2-43c6-b722-ea398719035d"),
                            Name = "Envestnet",
                            Price = 84
                        },
                        new
                        {
                            Id = new Guid("002327cf-dbf8-4003-93e4-43a03f5fceb5"),
                            Name = "Epazz",
                            Price = 51
                        },
                        new
                        {
                            Id = new Guid("76b1f1ea-9c47-43b1-bd17-4f75b3e2eb6b"),
                            Name = "FlashZero",
                            Price = 58
                        },
                        new
                        {
                            Id = new Guid("5405a6bf-a0d2-4e3e-a598-cfc48a2cbcaf"),
                            Name = "Genesis",
                            Price = 13
                        },
                        new
                        {
                            Id = new Guid("d75d3245-d431-4b9d-a146-77112399e117"),
                            Name = "InterNAP",
                            Price = 94
                        },
                        new
                        {
                            Id = new Guid("e58a89f9-7b29-4e71-a0ca-9ccb9b561cde"),
                            Name = "MeetMe",
                            Price = 35
                        },
                        new
                        {
                            Id = new Guid("3619c62f-3ddd-4c56-b29e-913f2b9d96df"),
                            Name = "Netease",
                            Price = 34
                        },
                        new
                        {
                            Id = new Guid("8c52e4c7-46b1-48a5-b7ac-a3a3e0d0ba59"),
                            Name = "Qihoo",
                            Price = 67
                        });
                });

            modelBuilder.Entity("StockMarketApp.Models.Order", b =>
                {
                    b.HasOne("StockMarketApp.Models.Broker", "broker")
                        .WithMany("Orders")
                        .HasForeignKey("BrokerId");

                    b.HasOne("StockMarketApp.Models.Person", "client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId");

                    b.HasOne("StockMarketApp.Models.Stock", "stock")
                        .WithMany("Orders")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StockMarketApp.Models.Person", b =>
                {
                    b.HasOne("StockMarketApp.Models.Broker")
                        .WithMany("Clients")
                        .HasForeignKey("BrokerId");
                });
#pragma warning restore 612, 618
        }
    }
}
